<Project Sdk="Microsoft.NET.Sdk">

	<Sdk Name="Aspire.AppHost.Sdk" Version="9.3.1" />

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<UserSecretsId>907d9ca2-5efe-4b39-9da1-ebc5f45e044f</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Aspire.Hosting.AppHost" />
		<PackageReference Include="Aspire.Hosting.PostgreSQL" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Nontitle_API\Nontitle_API.csproj" />
	</ItemGroup>

</Project>
